Usecase/display recipe details
parkhangorodsky/BitByteBistro pull request #50
Opened 2024-07-27 05:45 UTC by seonghyunban

Created Display Recipe Detail Usecase.

2024-07-28 02:25 UTC, parkhangorodsky approved these changes
this is amazing, thanks for getting this done!

2024-07-28 16:33 UTC, parkhangorodsky commented
oh true, can you link an issue please?

2024-07-29 04:02 UTC, parkhangorodsky requested changes
mostly good

can you add the directory structure? - it seems that everything in display_recipe_detail is flat in that directory.

2024-07-29 17:08 UTC, hhpfiona requested changes

2024-07-29 17:08 UTC, hhpfiona commented on src/main/java/frameworks/gui/SwingGUI.java
so we're pulling controller from config instead of making new. is this part of how to "link" login data?

2024-07-29 17:08 UTC, hhpfiona commented on src/main/java/use_cases/_common/gui_common/abstractions/PopUpView.java
where is this used? maybe some more documentation on that

2024-07-29 17:13 UTC, hhpfiona commented
also, one thing i noticed is that when clicking on the details for recipes, the scroll down to see all information is very slow.

2024-07-29 20:25 UTC, merged